name: "Sync Verisure Component Code"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 2"

env:
  NODE_VERSION: 20

jobs:
  sync-verisure-component-code:
    name: Sync Verisure Component Code
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        name: Checkout repository

      - name: Update Verisure Component Code
        run: |
          ./scripts/update.sh

      - name: Commit new changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add custom_components/verisure
          git diff --staged --exit-code && echo "No changes to the verisure component code on this run; exiting." && exit 0 || true
          git commit -nm "Update Verisure component code"
          git tag "${{ env.HOMEASSISTANT_VERSION }}"
          git push --tags

      - name: Create Github Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "${{ env.HOMEASSISTANT_VERSION }}" --latest --generate-notes --title "${{ env.HOMEASSISTANT_VERSION }}"